version: '3'
services:
  api-gateway:
    image: angelvr22/api-gateway:1.0
    ports:
      - "4000:3000"
    depends_on:
      - task-service
      - user-service
      - notification-service
      - team-service
    networks:
      - microservices-network

  task-service:
    image: angelvr22/task-service:1.0
    networks:
      - microservices-network

  user-service:
    image: angelvr22/user-service:1.0
    networks:
      - microservices-network

  notification-service:
    image: angelvr22/notification-service:1.0
    networks:
      - microservices-network

  team-service:
    image: angelvr22/team-service:1.0
    networks:
      - microservices-network

  frontend:
    image: angelvr22/frontend:1.0
    ports:
      - "8080:80"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
